FROM python:3.9-slim

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY IntelPyTorch_InferenceOptimizations_AMX_BF16_INT8.py IntelPyTorch_InferenceOptimizations_AMX_BF16_INT8.py
